//国家数组
module.exports = {
  continents: {
    Asia: {
      enName: 'Asia',
      cnName: '亚洲',
      countries: [
        { enName: 'Afghanistan', cnName: '阿富汗' },
        { enName: 'Bahrain', cnName: '巴林' },
        { enName: 'Bangladesh', cnName: '孟加拉国' },
        { enName: 'Bhutan', cnName: '不丹' },
        { enName: 'Brunei', cnName: '文莱' },
        { enName: 'Cambodia', cnName: '柬埔寨' },
        { enName: 'China', cnName: '中国' },
        { enName: 'Cyprus', cnName: '塞浦路斯' },
        { enName: 'Dem. Rep. Korea', cnName: '朝鲜' },
        { enName: 'Georgia', cnName: '格鲁吉亚' },
        { enName: 'India', cnName: '印度' },
        { enName: 'Indonesia', cnName: '印度尼西亚' },
        { enName: 'Iran', cnName: '伊朗' },
        { enName: 'Iraq', cnName: '伊拉克' },
        { enName: 'Israel', cnName: '以色列' },
        { enName: 'Japan', cnName: '日本' },
        { enName: 'Jordan', cnName: '约旦' },
        { enName: 'Kazakhstan', cnName: '哈萨克斯坦' },
        { enName: 'Korea', cnName: '韩国' },
        { enName: 'Kuwait', cnName: '科威特' },
        { enName: 'Kyrgyzstan', cnName: '吉尔吉斯斯坦' },
        { enName: 'Lao PDR', cnName: '老挝' },
        { enName: 'Lebanon', cnName: '黎巴嫩' },
        { enName: 'Malaysia', cnName: '马来西亚' },
        { enName: 'Mongolia', cnName: '蒙古' },
        { enName: 'Myanmar', cnName: '缅甸' },
        { enName: 'Nepal', cnName: '尼泊尔' },
        { enName: 'Oman', cnName: '阿曼' },
        { enName: 'Pakistan', cnName: '巴基斯坦' },
        { enName: 'Palestine', cnName: '巴勒斯坦' },
        { enName: 'Philippines', cnName: '菲律宾' },
        { enName: 'Qatar', cnName: '卡塔尔' },
        { enName: 'Saudi Arabia', cnName: '沙特阿拉伯' },
        { enName: 'Singapore', cnName: '新加坡' },
        { enName: 'Siachen Glacier', cnName: '锡亚琴冰川' },
        { enName: 'Sri Lanka', cnName: '斯里兰卡' },
        { enName: 'Syria', cnName: '叙利亚' },
        { enName: 'Tajikistan', cnName: '塔吉克斯坦' },
        { enName: 'Thailand', cnName: '泰国' },
        { enName: 'Timor-Leste', cnName: '东帝汶' },
        { enName: 'Turkey', cnName: '土耳其' },
        { enName: 'Turkmenistan', cnName: '土库曼斯坦' },
        { enName: 'United Arab Emirates', cnName: '阿拉伯联合酋长国' },
        { enName: 'Uzbekistan', cnName: '乌兹别克斯坦' },
        { enName: 'Vietnam', cnName: '越南' },
        { enName: 'Yemen', cnName: '也门' },
      ],
    },
    Europe: {
      enName: 'Europe',
      cnName: '欧洲',
      countries: [
        { enName: 'Aland', cnName: '奥兰群岛' },
        { enName: 'Albania', cnName: '阿尔巴尼亚' },
        { enName: 'Andorra', cnName: '安道尔' },
        { enName: 'Armenia', cnName: '亚美尼亚' },
        { enName: 'Austria', cnName: '奥地利' },
        { enName: 'Azerbaijan', cnName: '阿塞拜疆' },
        { enName: 'Belarus', cnName: '白俄罗斯' },
        { enName: 'Belgium', cnName: '比利时' },
        { enName: 'Bosnia and Herz.', cnName: '波斯尼亚和黑塞哥维那' },
        { enName: 'Bulgaria', cnName: '保加利亚' },
        { enName: 'Croatia', cnName: '克罗地亚' },
        { enName: 'Czech Rep.', cnName: '捷克' },
        { enName: 'Denmark', cnName: '丹麦' },
        { enName: 'Estonia', cnName: '爱沙尼亚' },
        { enName: 'Faeroe Is.', cnName: '法罗群岛' },
        { enName: 'Finland', cnName: '芬兰' },
        { enName: 'France', cnName: '法国' },
        { enName: 'Germany', cnName: '德国' },
        { enName: 'Greece', cnName: '希腊' },
        { enName: 'Hungary', cnName: '匈牙利' },
        { enName: 'Iceland', cnName: '冰岛' },
        { enName: 'Ireland', cnName: '爱尔兰' },
        { enName: 'Isle of Man', cnName: '马恩岛' },
        { enName: 'Italy', cnName: '意大利' },
        { enName: 'Jersey', cnName: '泽西岛' },
        { enName: 'Latvia', cnName: '拉脱维亚' },
        { enName: 'Liechtenstein', cnName: '列支敦士登' },
        { enName: 'Lithuania', cnName: '立陶宛' },
        { enName: 'Luxembourg', cnName: '卢森堡' },
        { enName: 'Macedonia', cnName: '马其顿' },
        { enName: 'Malta', cnName: '马耳他' },
        { enName: 'Moldova', cnName: '摩尔多瓦' },
        { enName: 'Montenegro', cnName: '黑山' },
        { enName: 'N. Cyprus', cnName: '北塞浦路斯' },
        { enName: 'Netherlands', cnName: '荷兰' },
        { enName: 'Norway', cnName: '挪威' },
        { enName: 'Poland', cnName: '波兰' },
        { enName: 'Portugal', cnName: '葡萄牙' },
        { enName: 'Romania', cnName: '罗马尼亚' },
        { enName: 'Russia', cnName: '俄罗斯' },
        { enName: 'Serbia', cnName: '塞尔维亚' },
        { enName: 'Slovakia', cnName: '斯洛伐克' },
        { enName: 'Slovenia', cnName: '斯洛文尼亚' },
        { enName: 'Spain', cnName: '西班牙' },
        { enName: 'Sweden', cnName: '瑞典' },
        { enName: 'Switzerland', cnName: '瑞士' },
        { enName: 'Ukraine', cnName: '乌克兰' },
        { enName: 'United Kingdom', cnName: '英国' },
      ],
    },
    Africa: {
      enName: 'Africa',
      cnName: '非洲',
      countries: [
        { enName: 'Algeria', cnName: '阿尔及利亚' },
        { enName: 'Angola', cnName: '安哥拉' },
        { enName: 'Benin', cnName: '贝宁' },
        { enName: 'Botswana', cnName: '博茨瓦纳' },
        { enName: 'Burkina Faso', cnName: '布基纳法索' },
        { enName: 'Burundi', cnName: '布隆迪' },
        { enName: 'Cameroon', cnName: '喀麦隆' },
        { enName: 'Cape Verde', cnName: '佛得角' },
        { enName: 'Central African Rep.', cnName: '中非共和国' },
        { enName: 'Chad', cnName: '乍得' },
        { enName: 'Comoros', cnName: '科摩罗' },
        { enName: 'Congo', cnName: '刚果（布）' },
        { enName: "Côte d'Ivoire", cnName: '科特迪瓦' },
        { enName: 'Dem. Rep. Congo', cnName: '刚果（金）' },
        { enName: 'Djibouti', cnName: '吉布提' },
        { enName: 'Egypt', cnName: '埃及' },
        { enName: 'Eq. Guinea', cnName: '赤道几内亚' },
        { enName: 'Eritrea', cnName: '厄立特里亚' },
        { enName: 'Ethiopia', cnName: '埃塞俄比亚' },
        { enName: 'Gabon', cnName: '加蓬' },
        { enName: 'Gambia', cnName: '冈比亚' },
        { enName: 'Ghana', cnName: '加纳' },
        { enName: 'Guinea', cnName: '几内亚' },
        { enName: 'Guinea-Bissau', cnName: '几内亚比绍' },
        { enName: 'Kenya', cnName: '肯尼亚' },
        { enName: 'Lesotho', cnName: '莱索托' },
        { enName: 'Liberia', cnName: '利比里亚' },
        { enName: 'Libya', cnName: '利比亚' },
        { enName: 'Madagascar', cnName: '马达加斯加' },
        { enName: 'Malawi', cnName: '马拉维' },
        { enName: 'Mali', cnName: '马里' },
        { enName: 'Mauritania', cnName: '毛里塔尼亚' },
        { enName: 'Mauritius', cnName: '毛里求斯' },
        { enName: 'Morocco', cnName: '摩洛哥' },
        { enName: 'Mozambique', cnName: '莫桑比克' },
        { enName: 'Namibia', cnName: '纳米比亚' },
        { enName: 'Niger', cnName: '尼日尔' },
        { enName: 'Nigeria', cnName: '尼日利亚' },
        { enName: 'Rwanda', cnName: '卢旺达' },
        { enName: 'São Tomé and Principe', cnName: '圣多美和普林西比' },
        { enName: 'Senegal', cnName: '塞内加尔' },
        { enName: 'Seychelles', cnName: '塞舌尔' },
        { enName: 'Sierra Leone', cnName: '塞拉利昂' },
        { enName: 'Somalia', cnName: '索马里' },
        { enName: 'South Africa', cnName: '南非' },
        { enName: 'S. Sudan', cnName: '南苏丹' },
        { enName: 'Sudan', cnName: '苏丹' },
        { enName: 'Swaziland', cnName: '斯威士兰' },
        { enName: 'Tanzania', cnName: '坦桑尼亚' },
        { enName: 'Togo', cnName: '多哥' },
        { enName: 'Tunisia', cnName: '突尼斯' },
        { enName: 'Uganda', cnName: '乌干达' },
        { enName: 'W. Sahara', cnName: '西撒哈拉' },
        { enName: 'Zambia', cnName: '赞比亚' },
        { enName: 'Zimbabwe', cnName: '津巴布韦' },
      ],
    },
    'North America': {
      enName: 'North America',
      cnName: '北美洲',
      countries: [
        { enName: 'American Samoa', cnName: '美属萨摩亚' },
        { enName: 'Antigua and Barb.', cnName: '安提瓜和巴布达' },
        { enName: 'Bahamas', cnName: '巴哈马' },
        { enName: 'Barbados', cnName: '巴巴多斯' },
        { enName: 'Belize', cnName: '伯利兹' },
        { enName: 'Bermuda', cnName: '百慕大' },
        { enName: 'Canada', cnName: '加拿大' },
        { enName: 'Cayman Is.', cnName: '开曼群岛' },
        { enName: 'Costa Rica', cnName: '哥斯达黎加' },
        { enName: 'Cuba', cnName: '古巴' },
        { enName: 'Curaçao', cnName: '库拉索' },
        { enName: 'Dominica', cnName: '多米尼克' },
        { enName: 'Dominican Rep.', cnName: '多米尼加' },
        { enName: 'El Salvador', cnName: '萨尔瓦多' },
        { enName: 'Greenland', cnName: '格陵兰' },
        { enName: 'Grenada', cnName: '格林纳达' },
        { enName: 'Guam', cnName: '关岛' },
        { enName: 'Guatemala', cnName: '危地马拉' },
        { enName: 'Haiti', cnName: '海地' },
        { enName: 'Honduras', cnName: '洪都拉斯' },
        { enName: 'Jamaica', cnName: '牙买加' },
        { enName: 'Mexico', cnName: '墨西哥' },
        { enName: 'Montserrat', cnName: '蒙特塞拉特' },
        { enName: 'N. Mariana Is.', cnName: '北马里亚纳群岛' },
        { enName: 'Nicaragua', cnName: '尼加拉瓜' },
        { enName: 'Panama', cnName: '巴拿马' },
        { enName: 'Puerto Rico', cnName: '波多黎各' },
        { enName: 'Saint Lucia', cnName: '圣卢西亚' },
        { enName: 'St. Pierre and Miquelon', cnName: '圣皮埃尔和密克隆' },
        { enName: 'St. Vin. and Gren.', cnName: '圣文森特和格林纳丁斯' },
        { enName: 'Trinidad and Tobago', cnName: '特立尼达和多巴哥' },
        { enName: 'Turks and Caicos Is.', cnName: '特克斯和凯科斯群岛' },
        { enName: 'U.S. Virgin Is.', cnName: '美属维尔京群岛' },
        { enName: 'United States', cnName: '美国' },
      ],
    },
    'South America': {
      enName: 'South America',
      cnName: '南美洲',
      countries: [
        { enName: 'Argentina', cnName: '阿根廷' },
        { enName: 'Bolivia', cnName: '玻利维亚' },
        { enName: 'Brazil', cnName: '巴西' },
        { enName: 'Chile', cnName: '智利' },
        { enName: 'Colombia', cnName: '哥伦比亚' },
        { enName: 'Ecuador', cnName: '厄瓜多尔' },
        { enName: 'Falkland Is.', cnName: '福克兰群岛' },
        { enName: 'Guyana', cnName: '圭亚那' },
        { enName: 'Paraguay', cnName: '巴拉圭' },
        { enName: 'Peru', cnName: '秘鲁' },
        { enName: 'Suriname', cnName: '苏里南' },
        { enName: 'Uruguay', cnName: '乌拉圭' },
        { enName: 'Venezuela', cnName: '委内瑞拉' },
      ],
    },
    Oceania: {
      enName: 'Oceania',
      cnName: '大洋洲',
      countries: [
        { enName: 'Australia', cnName: '澳大利亚' },
        { enName: 'Fiji', cnName: '斐济' },
        { enName: 'Fr. Polynesia', cnName: '法属波利尼西亚' },
        { enName: 'Kiribati', cnName: '基里巴斯' },
        { enName: 'Micronesia', cnName: '密克罗尼西亚联邦' },
        { enName: 'Nauru', cnName: '瑙鲁' },
        { enName: 'New Caledonia', cnName: '新喀里多尼亚' },
        { enName: 'New Zealand', cnName: '新西兰' },
        { enName: 'Niue', cnName: '纽埃' },
        { enName: 'Palau', cnName: '帕劳' },
        { enName: 'Papua New Guinea', cnName: '巴布亚新几内亚' },
        { enName: 'Samoa', cnName: '萨摩亚' },
        { enName: 'Solomon Is.', cnName: '所罗门群岛' },
        { enName: 'Tonga', cnName: '汤加' },
        { enName: 'Vanuatu', cnName: '瓦努阿图' },
      ],
    },
    Antarctica: {
      enName: 'Antarctica',
      cnName: '南极洲',
      countries: [
        { enName: 'Br. Indian Ocean Ter.', cnName: '英属印度洋领地' },
        { enName: 'Fr. S. Antarctic Lands', cnName: '法属南部和南极领地' },
        { enName: 'Heard I. and McDonald Is.', cnName: '赫德岛和麦克唐纳群岛' },
        {
          enName: 'S. Geo. and S. Sandw. Is.',
          cnName: '南乔治亚岛和南桑威奇群岛',
        },
        { enName: 'Saint Helena', cnName: '圣赫勒拿' },
      ],
    },
  },
};
