// 指标字段
const indicatorData = [
  // 1. 城镇化进程维度
  {
    indicatorCnName: '城镇化进程维度',
    indicatorEnName: 'urbanizationProcessDimension',
    weight: 0.027,
    secondaryIndicators: [
      {
        indicatorCnName: '线性表征',
        indicatorEnName: 'linearCharacterization',
        weight: 0.352,
        detailedIndicators: [
          {
            indicatorCnName: '城镇化水平',
            indicatorEnName: 'urbanizationLevel',
            weight: 0.432,
            unit: '%',
            description: '常住人口/总人口',
          },
          {
            indicatorCnName: '稳态趋势',
            indicatorEnName: 'steadyStateTrend',
            weight: 0.09,
            unit: '个',
            description: '稳态和趋势样本数量',
          },
          {
            indicatorCnName: '进程类型',
            indicatorEnName: 'processType',
            weight: 0.478,
            unit: '',
            description: '诺瑟姆型、拓展型、波型',
          },
        ],
      },
      {
        indicatorCnName: '波性表征',
        indicatorEnName: 'waveCharacterization',
        weight: 0.648,
        detailedIndicators: [
          {
            indicatorCnName: '增效与减效时长比',
            indicatorEnName: 'gainLossDurationRatio',
            weight: 0.484,
            unit: '',
            description: '波动谷值到相邻峰值的时间/峰值到相邻谷值的时间',
          },
          {
            indicatorCnName: '最大偏离值',
            indicatorEnName: 'maxDeviationValue',
            weight: 0.023,
            unit: '%',
            description: '城镇化残差序列在0%以上/以下的波动最大峰值',
          },
          {
            indicatorCnName: '周期组合',
            indicatorEnName: 'periodCombination',
            weight: 0.493,
            unit: '个',
            description: '不同周期波长组合的个数',
          },
        ],
      },
    ],
  },
  // 2. 人性动力维度
  {
    indicatorCnName: '人性动力维度',
    indicatorEnName: 'humanDynamicsDimension',
    weight: 0.525,
    secondaryIndicators: [
      {
        indicatorCnName: '生计欲望',
        indicatorEnName: 'livelihoodDesire',
        weight: 0.472,
        detailedIndicators: [
          {
            indicatorCnName: '人口规模',
            indicatorEnName: 'populationSize',
            weight: 0.11,
            unit: '人',
            description: '年人口总量',
          },
          {
            indicatorCnName: '农业就业率',
            indicatorEnName: 'agriculturalEmploymentRate',
            weight: 0.01,
            unit: '%',
            description: '从事农业相关就业人数',
          },
          {
            indicatorCnName: '非农就业率',
            indicatorEnName: 'nonAgriculturalEmploymentRate',
            weight: 0.012,
            unit: '%',
            description: '从事农业以外的就业人数',
          },
          {
            indicatorCnName: '粗出生率',
            indicatorEnName: 'crudeBirthRate',
            weight: 0.025,
            unit: '人/千人',
            description: '人口出生人口/总人数*100%',
          },
          {
            indicatorCnName: '粗死亡率',
            indicatorEnName: 'crudeDeathRate',
            weight: 0.006,
            unit: '人/千人',
            description: '人口死亡人口/总人数*100%',
          },
          {
            indicatorCnName: '管理人员工资',
            indicatorEnName: 'managerialStaffSalary',
            weight: 0.092,
            unit: '美元/月',
            description: '管理人员月平均工资',
          },
          {
            indicatorCnName: '专业人员工资',
            indicatorEnName: 'professionalStaffSalary',
            weight: 0.091,
            unit: '美元/月',
            description: '专业人员月平均工资',
          },
          {
            indicatorCnName: '技术人员工资',
            indicatorEnName: 'technicalStaffSalary',
            weight: 0.088,
            unit: '美元/月',
            description: '技术人员月平均工资',
          },
          {
            indicatorCnName: '文书人员工资',
            indicatorEnName: 'clericalStaffSalary',
            weight: 0.089,
            unit: '美元/月',
            description: '文书人员月平均工资',
          },
          {
            indicatorCnName: '服务人员工资',
            indicatorEnName: 'serviceStaffSalary',
            weight: 0.094,
            unit: '美元/月',
            description: '服务人员月平均工资',
          },
          {
            indicatorCnName: '工艺人员工资',
            indicatorEnName: 'craftsmenSalary',
            weight: 0.095,
            unit: '美元/月',
            description: '工艺人员月平均工资',
          },
          {
            indicatorCnName: '工厂人员工资',
            indicatorEnName: 'factoryWorkerSalary',
            weight: 0.098,
            unit: '美元/月',
            description: '工厂人员月平均工资',
          },
          {
            indicatorCnName: '农林渔业人员工资',
            indicatorEnName: 'agricultureForestryFisherySalary',
            weight: 0.095,
            unit: '美元/月',
            description: '农林渔业人员月平均工资',
          },
          {
            indicatorCnName: '基本职业人员工资',
            indicatorEnName: 'elementaryOccupationsSalary',
            weight: 0.095,
            unit: '美元/月',
            description: '基本职业人员月平均工资',
          },
        ],
      },
      {
        indicatorCnName: '享乐欲望',
        indicatorEnName: 'hedonicDesire',
        weight: 0.25,
        description: '反映居民对生活质量、休闲娱乐和精神满足的追求。',
        detailedIndicators: [
          {
            indicatorCnName: '劳动参与率',
            indicatorEnName: 'laborForceParticipationRate',
            weight: 0.031,
            unit: '%',
            description: '全部就业人口的总和/16-64岁人口*100%',
          },
          {
            indicatorCnName: '管理人员比重',
            indicatorEnName: 'managerialStaffProportion',
            weight: 0.136,
            unit: '%',
            description: '管理人员人数/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '专业人员比重',
            indicatorEnName: 'professionalStaffProportion',
            weight: 0.124,
            unit: '%',
            description: '专业人员/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '技术人员比重',
            indicatorEnName: 'technicalStaffProportion',
            weight: 0.126,
            unit: '%',
            description: '技术人员/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '文书人员比重',
            indicatorEnName: 'clericalStaffProportion',
            weight: 0.125,
            unit: '%',
            description: '文书人员/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '服务人员比重',
            indicatorEnName: 'serviceStaffProportion',
            weight: 0.092,
            unit: '%',
            description: '服务人员/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '工艺人员比重',
            indicatorEnName: 'craftsmenProportion',
            weight: 0.088,
            unit: '%',
            description: '工艺人员/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '工厂人员比重',
            indicatorEnName: 'factoryWorkerProportion',
            weight: 0.096,
            unit: '%',
            description: '工厂人员/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '农林渔业人员比重',
            indicatorEnName: 'agricultureForestryFisheryProportion',
            weight: 0.097,
            unit: '%',
            description: '农林渔业人员/所有职业就业人数*100%',
          },
          {
            indicatorCnName: '基本职业人员比重',
            indicatorEnName: 'elementaryOccupationsProportion',
            weight: 0.085,
            unit: '%',
            description: '基本职业人员/所有职业就业人数*100%',
          },
        ],
      },
      {
        indicatorCnName: '创新欲望',
        indicatorEnName: 'innovationDesire',
        weight: 0.278,
        description: '反映社会对知识、技术和创新的追求与投入。',
        detailedIndicators: [
          {
            indicatorCnName: '高等院校入学率',
            indicatorEnName: 'higherEducationEnrollmentRate',
            weight: 0.102,
            unit: '%',
            description: '高等院校入学人口/总人数*100%',
          },
          {
            indicatorCnName: '公共教育支出比重',
            indicatorEnName: 'publicEducationExpenditureProportion',
            weight: 0.033,
            unit: '%',
            description: '公共教育支出占政府财政支出比值*100%',
          },
          {
            indicatorCnName: 'R&D研究人员',
            indicatorEnName: 'rdResearchers',
            weight: 0.195,
            unit: '人/每百万人',
            description: '参与R&D研究每百万人的专业人员数量',
          },
          {
            indicatorCnName: 'R&D研究经费支出',
            indicatorEnName: 'rdExpenditure',
            weight: 0.177,
            unit: '%',
            description: 'R&D研究经费支出/GDP*100%',
          },
          {
            indicatorCnName: '知识产权使用费接收',
            indicatorEnName: 'intellectualPropertyChargesReceived',
            weight: 0.266,
            unit: '美元',
            description: '知识产权使用费收款',
          },
          {
            indicatorCnName: '知识产权使用费支出',
            indicatorEnName: 'intellectualPropertyChargesPaid',
            weight: 0.227,
            unit: '美元',
            description: '知识产权使用费付款',
          },
        ],
      },
    ],
  },
  // 3. 物性动力维度
  {
    indicatorCnName: '物性动力维度',
    indicatorEnName: 'materialDynamicsDimension',
    weight: 0.129,
    secondaryIndicators: [
      {
        indicatorCnName: '动力模式',
        indicatorEnName: 'dynamicMode',
        weight: 0.2,
        detailedIndicators: [
          {
            indicatorCnName: '第一产业增加值比重',
            indicatorEnName: 'primaryIndustryValueAddedRatio',
            weight: 0.072,
            unit: '%',
            description: '第一产业增加值/GDP*100%',
          },
          {
            indicatorCnName: '第二产业增加值比重',
            indicatorEnName: 'secondaryIndustryValueAddedRatio',
            weight: 0.286,
            unit: '%',
            description: '第二产业增加值/GDP*100%',
          },
          {
            indicatorCnName: '第三产业增加值比重',
            indicatorEnName: 'tertiaryIndustryValueAddedRatio',
            weight: 0.293,
            unit: '%',
            description: '第三产业增加值/GDP*100%',
          },
          {
            indicatorCnName: '商品贸易额',
            indicatorEnName: 'commodityTradeVolume',
            weight: 0.349,
            unit: '%',
            description: '商品贸易额/GDP*100%',
          },
        ],
      },
      {
        indicatorCnName: '动力环境',
        indicatorEnName: 'dynamicEnvironment',
        weight: 0.088,
        detailedIndicators: [
          {
            indicatorCnName: 'D1核心动力贡献率',
            indicatorEnName: 'd1CorePowerContributionRate',
            weight: 0.291,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D2资源利用贡献率',
            indicatorEnName: 'd2ResourceUtilizationContributionRate',
            weight: 0.221,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D3社会成本贡献率',
            indicatorEnName: 'd3SocialCostContributionRate',
            weight: 0.041,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D4建设成本贡献率',
            indicatorEnName: 'd4ConstructionCostContributionRate',
            weight: 0.036,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D5市场环境贡献率',
            indicatorEnName: 'd5MarketEnvironmentContributionRate',
            weight: 0.248,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D6运行成本贡献率',
            indicatorEnName: 'd6OperatingCostContributionRate',
            weight: 0.045,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D7外贸能力贡献率',
            indicatorEnName: 'd7ForeignTradeCapacityContributionRate',
            weight: 0.031,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D8创新能力贡献率',
            indicatorEnName: 'd8InnovationCapacityContributionRate',
            weight: 0.052,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
          {
            indicatorCnName: 'D9韧性环境贡献率',
            indicatorEnName: 'd9ResilienceEnvironmentContributionRate',
            weight: 0.035,
            unit: '%',
            description: '非标准化系数/非标准系数总和*100%',
          },
        ],
      },
      {
        indicatorCnName: '资源投入',
        indicatorEnName: 'resourceInput',
        weight: 0.712,
        detailedIndicators: [
          {
            indicatorCnName: 'GDP总量',
            indicatorEnName: 'gdpTotal',
            weight: 0.331,
            unit: '亿美元',
            description: '年GDP总量',
          },
          {
            indicatorCnName: '人均GDP',
            indicatorEnName: 'gdpPerCapita',
            weight: 0.224,
            unit: '美元',
            description: 'GDP总量/总人数*100%',
          },
          {
            indicatorCnName: '自然资源租金总额(占GDP的百分比)',
            indicatorEnName: 'totalNaturalResourceRents',
            weight: 0.015,
            unit: '%',
            description: '自然资源租金总额/GDP*100%',
          },
          {
            indicatorCnName: 'GDP单位能源消耗',
            indicatorEnName: 'gdpPerUnitOfEnergyUse',
            weight: 0.217,
            unit: '千吨/亿美元',
            description: 'GDP总量/石油消耗总量*100%',
          },
          {
            indicatorCnName: '移动电话用户',
            indicatorEnName: 'mobilePhoneUsers',
            weight: 0.199,
            unit: '户/百人',
            description: '使用移动电话的人数',
          },
          {
            indicatorCnName: '固定宽带用户',
            indicatorEnName: 'fixedBroadbandUsers',
            weight: 0.014,
            unit: '户/百人',
            description: '使用固定宽带的人数',
          },
        ],
      },
    ],
  },
  // 4. 空间动力维度
  {
    indicatorCnName: '空间动力维度',
    indicatorEnName: 'spatialDynamicsDimension',
    weight: 0.319,
    secondaryIndicators: [
      {
        indicatorCnName: '扩散集聚',
        indicatorEnName: 'diffusionAndAgglomeration',
        weight: 0.266,
        detailedIndicators: [
          {
            indicatorCnName: '货物和服务进口',
            indicatorEnName: 'importsOfGoodsAndServices',
            weight: 0.308,
            unit: '亿美元',
            description: '货物和服务进口总额',
          },
          {
            indicatorCnName: '货物和服务出口',
            indicatorEnName: 'exportsOfGoodsAndServices',
            weight: 0.301,
            unit: '亿美元',
            description: '货物和服务出口总额',
          },
          {
            indicatorCnName: 'D5市场环境贡献值',
            indicatorEnName: 'd5MarketEnvironmentContributionValue',
            weight: 0.391,
            unit: '%',
            description: '市场环境D5/GDP总和*100%',
          },
        ],
      },
      {
        indicatorCnName: '规模位序',
        indicatorEnName: 'sizeRank',
        weight: 0.192,
        detailedIndicators: [
          {
            indicatorCnName: '进口成本',
            indicatorEnName: 'importCosts',
            weight: 0.008,
            unit: '美元',
            description: '进口成本（边境合规）',
          },
          {
            indicatorCnName: '出口成本',
            indicatorEnName: 'exportCosts',
            weight: 0.011,
            unit: '美元',
            description: '出口成本（边境合规）',
          },
          {
            indicatorCnName: 'D6运行成本贡献值',
            indicatorEnName: 'd6OperatingCostContributionValue',
            weight: 0.479,
            unit: '%',
            description: '运行成本D6/GDP总和*100%',
          },
          {
            indicatorCnName: 'D9韧性环境贡献值',
            indicatorEnName: 'd9ResilienceEnvironmentContributionValue',
            weight: 0.502,
            unit: '%',
            description: '韧性环境D9/GDP总和*100%',
          },
        ],
      },
      {
        indicatorCnName: '行为网络',
        indicatorEnName: 'behavioralNetwork',
        weight: 0.476,
        detailedIndicators: [
          {
            indicatorCnName: 'D2资源利用贡献值',
            indicatorEnName: 'd2ResourceUtilizationContributionValue',
            weight: 0.215,
            unit: '%',
            description: '资源利用D2/GDP总和*100%',
          },
          {
            indicatorCnName: 'D7外贸能力贡献值',
            indicatorEnName: 'd7ForeignTradeCapacityContributionValue',
            weight: 0.19,
            unit: '%',
            description: '外贸能力D7/GDP总和*100%',
          },
          {
            indicatorCnName: 'D3社会成本贡献值',
            indicatorEnName: 'd3SocialCostContributionValue',
            weight: 0.197,
            unit: '%',
            description: '社会成本D3/GDP总和*100%',
          },
          {
            indicatorCnName: 'D4建设成本贡献值',
            indicatorEnName: 'd4ConstructionCostContributionValue',
            weight: 0.197,
            unit: '%',
            description: '建设成本D4/GDP总和*100%',
          },
          {
            indicatorCnName: 'D8创新能力贡献值',
            indicatorEnName: 'd8InnovationCapacityContributionValue',
            weight: 0.201,
            unit: '%',
            description: '创新能力D8/GDP总和*100%',
          },
        ],
      },
      {
        indicatorCnName: '异质集聚',
        indicatorEnName: 'heterogeneousAgglomeration',
        weight: 0.066,
        detailedIndicators: [
          {
            indicatorCnName: '外国直接投资净流入',
            indicatorEnName: 'foreignDirectInvestmentNetInflows',
            weight: 0.223,
            unit: '亿美元',
            description: '外国直接投资净流入',
          },
          {
            indicatorCnName: '外国直接投资净流出',
            indicatorEnName: 'foreignDirectInvestmentNetOutflows',
            weight: 0.777,
            unit: '亿美元',
            description: '外国直接投资净流出',
          },
        ],
      },
    ],
  },
];

module.exports = indicatorData;
